services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      # Aqui cumprimos a regra do escopo: URL da API configurável
      - VITE_API_URL=http://localhost:8000
